baseURL = 'https://wassimseifeddine.com/'
languageCode = 'en-us'
languageName = "English"

title = 'Wassim Seifeddine'
theme = "LoveIt"
# Author config
staticDir = ['static']
defaultTheme = "light"
[author]
  name = "Wassim Seifeddine"
  email = "wassim@wassimseifeddine.com"
  link = "https://wassimseifeddine.com/"

# Menu config
[menu]
  [[menu.main]]
      weight = 1
      identifier = "about"
      # you can add extra information before the name (HTML format is supported), such as icons
      pre = '<i class="fa-solid fa-face-frown"></i>'
      # you can add extra information after the name (HTML format is supported), such as icons
      post = ""
      name = "About"
      url = "/about/"
      # title will be shown when you hover on this menu link
      title = ""
  # [[menu.main]]
  #   weight = 1
  #   pre = '<i class="fa-solid fa-newspaper"></i>'
  #   identifier = "posts"
  #   # you can add extra information before the name (HTML format is supported), such as icons
  #   # you can add extra information after the name (HTML format is supported), such as icons
  #   post = ""
  #   name = "Posts"
  #   url = "/posts/"
  #   # title will be shown when you hover on this menu link
    # title = ""
  [[menu.main]]
    weight = 2
    pre = '<i class="fa-solid fa-magnifying-glass"></i>'
    identifier = "publications"
    name = "Publications"
    url = "https://scholar.google.com/citations?user=x6EK09kAAAAJ&hl=en"
  [[menu.main]]
    weight = 3
    identifier = "resume"
    name = "Resume"
    url = "/wassim_seifeddine_cv.pdf"
  # [[menu.main]]
  #   weight = 2
  #   identifier = "tags"
  #   pre = ""
  #   post = ""
  #   name = "Tags"
  #   url = "/tags/"
  #   title = ""
  # [[menu.main]]
  #   weight = 3
  #   identifier = "categories"
  #   pre = ""
  #   post = ""
  #   name = "Categories"
  #   url = "/categories/"
  #   title = ""

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false